@OmPlatform_HostAddress = http://localhost:5223

GET {{OmPlatform_HostAddress}}/products/
Accept: application/json
###

GET {{OmPlatform_HostAddress}}/products/
Accept: application/json
###

GET {{OmPlatform_HostAddress}}/products/
Accept: application/json